version: '3.3'
services:
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_DATABASE: 'blackjack'
      # MYSQL_PASSWORD: ${DB_PASS}
      MYSQL_ALLOW_EMPTY_PASSWORD: true
      # MYSQL_ROOT_PASSWORD: ${DB_PASS}
    ports:
      # <Port exposed> : <MySQL Port running inside container>
      - '3306:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
  mailhog:
    image: mailhog/mailhog
    logging:
      driver: 'none'  # disable saving logs
    ports:
      - "1025:1025" # smtp server
      - "8025:8025" # web ui