spring:
  application:
    name: Blackjack
  main:
    banner-mode: off
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DB_HOST}:${DB_PORT}/bjdb?createDatabaseIfNotExist=true&useUnicode=true&characterEncoding=UTF-8
    username: ${DB_USER}
    password:
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      jakarta:
        persistence:
          shared-cache:
            mode: UNSPECIFIED
      hibernate:
        format_sql: true
    open-in-view: false
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/changelog-master.xml
  mvc:
    hidden-method:
      filter:
        enabled: true

google.recaptcha:
  enabled: true
  site: ${RECAPTCHA_SITE_KEY}
  secret: ${RECAPTCHA_SITE_SECRET}

auth:
  register:
    auto-login: false
  login:
    remember-me-key: ${REMEMBER_ME_KEY}
  activation-token:
    cleanup-cron: "*/60 */10 * * * *"
    expires-after-minutes: 60
  forgot-password-token:
    cleanup-cron: "*/60 */10 * * * *"
    expires-after-minutes: 30

# mail-hog: "localhost:8025"
mail:
  app-mail: ${APP_MAIL}
  host: ${MAIL_HOST}
  port: ${MAIL_PORT}
  username: ${MAIL_USER}
  password: ${MAIL_PASS}
  smtp-auth: true
  transport-protocol: smtp

logging:
  level:
    org:
      springframework:
        security: INFO